import { LunarSite } from './types';

export const lunarSites: LunarSite[] = [
  {
    id: 'A11',
    name: 'Apollo 11 - Sea of Tranquility',
    mission: 'Apollo 11',
    date: 'July 20, 1969',
    lat: 0.67409,
    lng: 23.47297,
    samples_returned: '21.5 kg',
    description: 'First human landing on the Moon. Collected basaltic rocks and breccias.',
    type: 'Apollo',
    geotechnical: { bulk_density: 1.61, friction_angle: 40.7, cohesion: 1.06, bearing_capacity: 10.0 }
  },
  {
    id: 'A12',
    name: 'Apollo 12 - Ocean of Storms',
    mission: 'Apollo 12',
    date: 'November 19, 1969',
    lat: -3.01239,
    lng: -23.42157,
    samples_returned: '34.3 kg',
    description: 'Landed near Surveyor 3. Collected basaltic samples from the Oceanus Procellarum.',
    type: 'Apollo',
    geotechnical: { bulk_density: 1.65, friction_angle: 31.8, cohesion: 1.04, bearing_capacity: 8.5 }
  },
  {
    id: 'A14',
    name: 'Apollo 14 - Fra Mauro',
    mission: 'Apollo 14',
    date: 'February 5, 1971',
    lat: -3.64530,
    lng: -17.47136,
    samples_returned: '42.3 kg',
    description: 'Landed in the Fra Mauro highlands. Collected impact-derived breccias.',
    type: 'Apollo',
    geotechnical: { bulk_density: 1.54, friction_angle: 39.0, cohesion: 0.18 }
  },
  {
    id: 'A15',
    name: 'Apollo 15 - Hadley-Apennine',
    mission: 'Apollo 15',
    date: 'July 30, 1971',
    lat: 26.13222,
    lng: 3.63386,
    samples_returned: '77.3 kg',
    description: 'First use of the Lunar Roving Vehicle. Collected samples from the Apennine Front and Hadley Rille.',
    type: 'Apollo',
    geotechnical: { bulk_density: 1.70, friction_angle: 48.1, cohesion: 0.77 }
  },
  {
    id: 'A16',
    name: 'Apollo 16 - Descartes Highlands',
    mission: 'Apollo 16',
    date: 'April 21, 1972',
    lat: -8.97301,
    lng: 15.49812,
    samples_returned: '95.7 kg',
    description: 'Landed in the lunar highlands. Collected ancient crustal rocks (anorthosites).',
    type: 'Apollo',
    geotechnical: { bulk_density: 1.68, friction_angle: 47.5, cohesion: 0.77 }
  },
  {
    id: 'A17',
    name: 'Apollo 17 - Taurus-Littrow',
    mission: 'Apollo 17',
    date: 'December 11, 1972',
    lat: 20.19080,
    lng: 30.77168,
    samples_returned: '110.5 kg',
    description: 'Final Apollo mission. Collected orange soil and diverse rock types from a valley.',
    type: 'Apollo',
    geotechnical: { bulk_density: 1.81, friction_angle: 36.7, cohesion: 0.60 }
  },
  {
    id: 'L16',
    name: 'Luna 16 - Mare Fecunditatis',
    mission: 'Luna 16',
    date: 'September 20, 1970',
    lat: -0.68,
    lng: 56.30,
    samples_returned: '101 g',
    description: 'First robotic sample return mission. Collected mare basalt.',
    type: 'Luna',
    geotechnical: { bulk_density: 1.44, friction_angle: 26.7, cohesion: 3.81 }
  },
  {
    id: 'L20',
    name: 'Luna 20 - Apollonius Highlands',
    mission: 'Luna 20',
    date: 'February 21, 1972',
    lat: 3.53,
    lng: 56.55,
    samples_returned: '55 g',
    description: 'Robotic sample return from the highlands near Mare Fecunditatis.',
    type: 'Luna',
    geotechnical: { bulk_density: 1.31, friction_angle: 24.4, cohesion: 4.66 }
  },
  {
    id: 'L24',
    name: 'Luna 24 - Mare Crisium',
    mission: 'Luna 24',
    date: 'August 18, 1976',
    lat: 12.71,
    lng: 62.21,
    samples_returned: '170 g',
    description: 'Final Soviet Luna mission. Collected samples from Mare Crisium.',
    type: 'Luna',
    geotechnical: { bulk_density: 1.85 }
  },
  {
    id: 'CE5',
    name: 'Chang\'e 5 - Oceanus Procellarum',
    mission: 'Chang\'e 5',
    date: 'December 1, 2020',
    lat: 43.0576,
    lng: -51.9161,
    samples_returned: '1.73 kg',
    description: 'First Chinese sample return mission. Collected young volcanic rocks.',
    type: 'Chang-e'
  },
  {
    id: 'CE3',
    name: "Chang'e 3 - Mare Imbrium",
    mission: "Chang'e 3",
    date: 'December 14, 2013',
    lat: 44.1214,
    lng: -19.5116,
    description: 'First Chinese lunar lander. Deployed Yutu rover on the Mare Imbrium.',
    type: 'Chang-e',
    geotechnical: { bulk_density: 1.63 }
  },
  {
    id: 'CE4',
    name: "Chang'e 4 - Von Karman Crater",
    mission: "Chang'e 4",
    date: 'January 3, 2019',
    lat: -45.4446,
    lng: 177.5991,
    description: 'First landing on the lunar far side. Deployed Yutu-2 rover in the South Pole-Aitken basin.',
    type: 'Chang-e'
  },
  {
    id: 'CH3',
    name: 'Chandrayaan 3 - Shiv Shakti Point',
    mission: 'Chandrayaan 3',
    date: 'August 23, 2023',
    lat: -69.3726,
    lng: 32.3188,
    description: 'First Indian lunar landing. Pragyan rover explored near the south pole.',
    type: 'Other',
    geotechnical: { bulk_density: 1.30 }
  },
  {
    id: 'S1',
    name: 'Surveyor 1 - Flamsteed P',
    mission: 'Surveyor 1',
    date: 'June 2, 1966',
    lat: -2.474,
    lng: -43.339,
    description: 'First US soft landing on the Moon. Conducted surface mechanics experiments.',
    type: 'Other',
    geotechnical: { bulk_density: 1.50, friction_angle: 41.7, cohesion: 4.52, bearing_capacity: 40.0 }
  },
  {
    id: 'S3',
    name: 'Surveyor 3 - Oceanus Procellarum',
    mission: 'Surveyor 3',
    date: 'April 20, 1967',
    lat: -3.0155,
    lng: -23.4219,
    description: 'Equipped with soil mechanics surface sampler. Later visited by Apollo 12.',
    type: 'Other',
    geotechnical: { bulk_density: 1.50, friction_angle: 42.0, cohesion: 0.47, bearing_capacity: 40.0 }
  },
  {
    id: 'L13',
    name: 'Luna 13 - Oceanus Procellarum',
    mission: 'Luna 13',
    date: 'December 24, 1966',
    lat: 18.87,
    lng: -62.05,
    description: 'Soviet lander with soil mechanics probe. Measured regolith bearing capacity.',
    type: 'Luna',
    geotechnical: { bulk_density: 0.80, friction_angle: 32.0, cohesion: 0.49, bearing_capacity: 68.0 }
  },
  {
    id: 'L17',
    name: 'Luna 17 - Mare Imbrium',
    mission: 'Luna 17',
    date: 'November 17, 1970',
    lat: 38.28,
    lng: -35.00,
    description: 'Deployed Lunokhod 1, the first robotic rover on the Moon.',
    type: 'Luna',
    geotechnical: { friction_angle: 34.3, cohesion: 2.25, bearing_capacity: 33.3 }
  },
  {
    id: 'L21',
    name: 'Luna 21 - Le Monnier Crater',
    mission: 'Luna 21',
    date: 'January 15, 1973',
    lat: 25.85,
    lng: 30.45,
    description: 'Deployed Lunokhod 2. Traversed 37 km across the lunar surface.',
    type: 'Luna',
    geotechnical: { friction_angle: 22.5, cohesion: 5.0, bearing_capacity: 40.0 }
  },
  {
    id: 'CE6',
    name: 'Chang\'e 6 - South Pole-Aitken Basin',
    mission: 'Chang\'e 6',
    date: 'June 2, 2024',
    lat: -41.6385,
    lng: -153.9852,
    samples_returned: '1.93 kg',
    description: 'First sample return from the lunar far side. Collected samples from the Apollo crater.',
    type: 'Chang-e'
  }
];
